### PR TITLE
Fix memory leak and also detect failed memory allocation

### LINKED ISSUE #632: [Bug]: ConfigDataGfx Does Not Free Memory
### Is there an existing issue for this?

- [X] I have searched existing issues

### Current Behavior

There is a memory leak in ConfigDataGfx, it allocates the policy, but does not free it.

### Expected Behavior

ConfigDataGfx should free any allocated memory.

### Steps To Reproduce

In the codebase.

### Build Environment

```markdown
- OS(s): N/A
- Tool Chain(s):All
- Targets Impacted:All
```

### Version Information

```text
Top of tree
```

### Urgency

Low

### Are you going to fix this?

Someone else needs to fix it

### Do you need maintainer feedback?

No maintainer feedback needed

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by vincent-j-zimmer**
## Description

Fixes #632 

This change is responsive to https://github.com/microsoft/mu_tiano_platforms/issues/632. It fixes a memory leak and also defends against a failed memory allocation.

- [ ] Impacts functionality?
- [ ] Impacts security?
- [ ] Breaking change?
- [ ] Includes tests?
- [ ] Includes documentation?

## How This Was Tested

Build test and boot to shell using QEMU

## Integration Instructions

N/A

### CODE REVIEW

**Review by os-d — APPROVED** [review]
We have stopped using MU_CHANGE tags in mu_tiano_platforms because we have completely forked from edk2, so nothing for us to track anymore. Otherwise LGTM!

File: Platforms/QemuQ35Pkg/ConfigKnobs/ConfigDataGfx/ConfigDataGfx.c [hunk 1]
```diff
@@ -64,16 +64,23 @@ ApplyGfxConfigToPolicy (
   GfxEnablePort0   = *(BOOLEAN *)ConfigBuffer;
   GfxSiliconPolicy = AllocateCopyPool (sizeof (DefaultQemuGfxPolicy), DefaultQemuGfxPolicy);
 
+  if (GfxSiliconPolicy == NULL) {
+    DEBUG ((DEBUG_ERROR, "Failed to allocate Policy structure\n"));
+    goto Exit;
```
Comment (makubacki) [inline Platforms/QemuQ35Pkg/ConfigKnobs/ConfigDataGfx/ConfigDataGfx.c:69]: It looks like `Status` will be uninitialized in this `goto Exit` path.

```suggestion
  if (GfxSiliconPolicy == NULL) {
    DEBUG ((DEBUG_ERROR, "Failed to allocate Policy structure\n"));
    Status = EFI_OUT_OF_RESOURCES;
    goto Exit;
```

Should add `EFI_OUT_OF_RESOURCES` to the function return values if this is done.

File: Platforms/QemuQ35Pkg/ConfigKnobs/ConfigDataGfx/ConfigDataGfx.c [hunk 2]
```diff
@@ -64,16 +64,23 @@ ApplyGfxConfigToPolicy (
   GfxEnablePort0   = *(BOOLEAN *)ConfigBuffer;
   GfxSiliconPolicy = AllocateCopyPool (sizeof (DefaultQemuGfxPolicy), DefaultQemuGfxPolicy);
 
+  if (GfxSiliconPolicy == NULL) {
+    DEBUG ((DEBUG_ERROR, "Failed to allocate Policy structure\n"));
+    goto Exit;
+  }  // Mu
```
Comment (makubacki) [inline Platforms/QemuQ35Pkg/ConfigKnobs/ConfigDataGfx/ConfigDataGfx.c:70]:
```suggestion
  }
```

Comment (makubacki) [reply Platforms/QemuQ35Pkg/ConfigKnobs/ConfigDataGfx/ConfigDataGfx.c:70]: As mentioned in Oliver's comment, the "Mu" comments can be dropped.

File: Platforms/QemuQ35Pkg/ConfigKnobs/ConfigDataGfx/ConfigDataGfx.c [hunk 3]
```diff
@@ -64,16 +64,23 @@ ApplyGfxConfigToPolicy (
...
+ 
   // We only translate the GFX ports #0 exposed to platform from conf data
   GfxSiliconPolicy[0].Power_State_Port = GfxEnablePort0;
 
   Status = SetPolicy (&gPolicyDataGFXGuid, POLICY_ATTRIBUTE_FINALIZED, GfxSiliconPolicy, sizeof (DefaultQemuGfxPolicy));
+
   if (EFI_ERROR (Status)) {
     DEBUG ((DEBUG_ERROR, "%a Failed to update GFX policy per configuration data - %r!!!\n", __func__, Status));
     ASSERT (FALSE);
```
Comment (makubacki) [inline Platforms/QemuQ35Pkg/ConfigKnobs/ConfigDataGfx/ConfigDataGfx.c:79]: Not related to your change, but I suggest updating this assert so it is more useful when printed. `ASSERT (FALSE)` is not very helpful.

```suggestion
    ASSERT_EFI_ERROR (Status);
```

File: Platforms/QemuQ35Pkg/ConfigKnobs/ConfigDataGfx/ConfigDataGfx.c [hunk 4]
```diff
@@ -64,16 +64,23 @@ ApplyGfxConfigToPolicy (
...
+    FreePool (GfxSiliconPolicy);   //Mu
     goto Exit;
   }
-
+  FreePool (GfxSiliconPolicy);   //Mu
```
Comment (makubacki) [inline Platforms/QemuQ35Pkg/ConfigKnobs/ConfigDataGfx/ConfigDataGfx.c:83]: Since all of these ultimately free the `GfxSiliconPolicy` buffer and all execution flows through the `Exit` label on return, I'd consider initialize `GfxSiliconPolicy` to `NULL` and then add a single free if the pointer is non-null in the `Exit` path.

```c
Exit:
  if (GfxSiliconPolicy != NULL) {
    FreePool (GfxSiliconPolicy);
  }
  
  return Status;
```

**Comment by makubacki** [comment]
CI is failing because uncrustify needs to be run. I suggest you do that following the VS Code plugin instructions here: https://github.com/tianocore/tianocore.github.io/wiki/EDK-II-Code-Formatting#recommended-usage-visual-studio-vs-code-plugin

**Review by makubacki — APPROVED** [review]

File: Platforms/QemuQ35Pkg/ConfigKnobs/ConfigDataGfx/ConfigDataGfx.c (hunk 4 above)
Comment (vincent-j-zimmer) [reply Platforms/QemuQ35Pkg/ConfigKnobs/ConfigDataGfx/ConfigDataGfx.c]: Good suggestion.  Updated w/ recommendations.

File: Platforms/QemuQ35Pkg/ConfigKnobs/ConfigDataGfx/ConfigDataGfx.c (hunk 3 above)
Comment (vincent-j-zimmer) [reply Platforms/QemuQ35Pkg/ConfigKnobs/ConfigDataGfx/ConfigDataGfx.c]: Good suggestion. Updated w/ recommendations.

File: Platforms/QemuQ35Pkg/ConfigKnobs/ConfigDataGfx/ConfigDataGfx.c (hunk 2 above)
Comment (vincent-j-zimmer) [reply Platforms/QemuQ35Pkg/ConfigKnobs/ConfigDataGfx/ConfigDataGfx.c]: Makes sense.  Updated w/ recommendation.

File: Platforms/QemuQ35Pkg/ConfigKnobs/ConfigDataGfx/ConfigDataGfx.c (hunk 1 above)
Comment (vincent-j-zimmer) [reply Platforms/QemuQ35Pkg/ConfigKnobs/ConfigDataGfx/ConfigDataGfx.c]: Good suggestion. Updated w/ recommendations.

**Review by kuqin12 — APPROVED** [review]
